import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <header className="bg-red-800">
            <nav className="flex justify-between p-4">
              <Link href="/">Home</Link>
              <Link href="/auth/login">Login</Link>
            </nav>
          </header>
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
